#Hugo configuration
title = "test"
baseURL = "https:\/\/asdf.safd.fs"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "safd.fs"
